create table if not exists public.event (
  id bigint primary key check (id = 1),
  draft_json jsonb not null,
  published_json jsonb not null,
  is_published boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.rsvp (
  id bigint generated by default as identity primary key,
  name text not null,
  attending text not null check (attending in ('yes', 'no')),
  party_size integer not null default 1 check (party_size between 1 and 12),
  contact text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.photo (
  id bigint generated by default as identity primary key,
  filename text not null unique,
  caption text not null default '',
  sort_order integer not null default 0,
  visible boolean not null default true
);

alter table public.event enable row level security;
alter table public.rsvp enable row level security;
alter table public.photo enable row level security;

-- The Flask server uses the Supabase service-role key and bypasses RLS.
-- The public photo bucket must be created in Storage and set to Public.
insert into storage.buckets (id, name, public)
values ('photos', 'photos', true)
on conflict (id) do update set public = true;
